---
title: "Digital_soil_mapping"
author: "Flueckiger_Rubens"
date: "2025-11-05"
output: 
  html_document:
    toc: TRUE
---

# Packages

```{r, message=FALSE, warning=FALSE}
library(ggplot2)
library(dplyr)
library(tidyr)
library(ranger)
library(caret)
library(plotROC)
```

# Load data sets

```{r}
df <- readRDS("../data_raw/df_digital_soil_mapping.rds")
```

#  Simple model

## Preprocessing

```{r}
# Specify target
target <- "waterlog.100"

# Specify predictors
predictors <- names(df)[14:ncol(df)]
```

```{r}
df_train <- df |> filter(dataset == "calibration") |> drop_na()
df_test <- df |> filter(dataset == "validation") |> drop_na()
```

## Model training

```{r}
rf_basic <- ranger(
  formula = factor(df_train[, target]) ~ ., # Model formula
  data = df_train[, predictors], # Target variable
  seed = 42,  # Seed for randomization to reproduce the same model
  num.threads = parallel::detectCores() - 1 # Use all but 1 CPU core for quick model training
)

# quick report and performance of trained model object
rf_basic
```

## Model evaluation

```{r}
# Predict waterlog.100 on test set
rf_eval <- predict(
  rf_basic, # Model
  data = df_test, # test set
  num.threads = parallel::detectCores() - 1
)

# Save predictions to validation df
df_eval <- data.frame(df_test$waterlog.100) # Observed
df_eval$pred <- rf_eval$predictions # Predicted

# Rename column
df_eval <- df_eval |>
  rename("waterlog.100" = "df_test.waterlog.100")
```

```{r}
conf_matrix <- confusionMatrix(
  data = df_eval$pred, # Predicted values
  reference = as.factor(df_eval$waterlog.100), # Observed values
  dnn = c("Predicted", "Observed") # Axis names of confusion matrix
)

# Quick report of statistical analysis
conf_matrix
```

```{r}
# Test set
balance_test <- df_eval |>
  group_by(waterlog.100) |> # Group by observations
  summarise(count = n()) # Count all 0's and 1's

# Training set
balance_train <- df_train |>
  group_by(waterlog.100) |> # Group by waterlog.100
  summarise(count = n())
```


# Variable selection

## Select variables

```{r}
set.seed(42)

# run the algorithm
bor <- Boruta::Boruta(
    y = df_train[, target], # Target variable
    x = df_train[, predictors], # All available predictors
    maxRuns = 50, # Number of iterations. Set to 30 or lower if it takes too long
    num.threads = parallel::detectCores()-1)

# obtain results: a data frame with all variables, ordered by their importance
df_bor <- Boruta::attStats(bor) |> 
  tibble::rownames_to_column() |> 
  arrange(dplyr::desc(meanImp))

# plot the importance result
ggplot(data = df_bor, aes(x = reorder(rowname, meanImp),
                          y = meanImp,
                          fill = decision)) +
  geom_bar(stat = "identity", width = 0.75) +
  scale_fill_manual(values = c("grey30", "tomato", "grey70")) +
  labs(
    x = "",
    y = "Variable importance",
    title = "Variable importance based on Boruta"
  ) +
  theme_bw() +
  coord_flip()
```

```{r}
predictors_selected <- df_bor |> 
  filter(decision == "Confirmed") |> # Filter all variables with "confirmed"
  pull(rowname) # Extract rownames from it
```

## Train new model

```{r}
rf_bor <- ranger( 
  formula = factor(df_train[, target]) ~ ., # target variable
  data = df_train[, predictors_selected], # Predictor variables
  seed = 42, # Specify the seed for randomization to reproduce the same model again
  num.threads = parallel::detectCores() - 1) 

# quick report and performance of trained model object
rf_bor
```

## Evaluate new model

```{r}
rf_eval_vs <- predict(
  rf_bor,           # RF model
  data = df_test,   # Predictor data
  num.threads = parallel::detectCores() - 1
)

# Save predictions to validation df
df_eval_vs <- data.frame(df_test$waterlog.100)
df_eval_vs$pred <- rf_eval_vs$predictions

# Rename column
df_eval_vs <- df_eval_vs |>
  rename("waterlog.100" = "df_test.waterlog.100")
```

```{r}
conf_matrix_vs <- confusionMatrix(
  data = df_eval_vs$pred,
  reference = as.factor(df_eval_vs$waterlog.100),
  dnn = c("Predicted", "Observed")
)
conf_matrix_vs
```

# Model optimization

## Hyperparameter adjustment

```{r}
# Create string with all variables
fun_pred <- paste(
  c("waterlog.100 ~", paste(predictors, collapse = " + ")),
  collapse = " "
)

# Convert into a caret-readable string
fun_pred <- formula(fun_pred)
```

```{r}
mod_cv <- train(
  fun_pred, # Model function
  data = df_train, # training set
  method = "ranger", # Random Forest model
  trControl = trainControl(
    method = "cv", # Cross-Validation method
    number = 5, # 5-Fold CV
    savePredictions = "final"
  ),
  tuneGrid = data.frame(
    .mtry = c(1, 2, 3, 4, 5, 10, 20, 30, 40, 50, 60, 70, 80),
    .min.node.size = c(1, 10, 20, 30, 40, 50, 100, 150, 200, 250, 300, 400, 500),
    .splitrule = "variance"
  ),
  metric = "MAE" # LOESS function
)
mod_cv
```

## Train optimized model

```{r}
rf_optim <- ranger( 
  formula = factor(df_train[, target]) ~ ., # target variable
  data = df_train[, predictors_selected], # Predictor variables
  mtry = 10, # Given from above
  min.node.size = 50, # Given from above
  seed = 42, # Specify the seed for randomization to reproduce the same model again
  num.threads = parallel::detectCores() - 1)

# quick report and performance of trained model object
rf_optim
```

## Evaluate optimized model

```{r}
rf_eval_optim <- predict(
  rf_optim, # RF model
  data = df_test, # Predictor data
  num.threads = parallel::detectCores() - 1
)

# Save predictions to validation df
df_eval_optim <- data.frame(df_test$waterlog.100)
df_eval_optim$pred <- rf_eval_optim$predictions

# Rename column
df_eval_optim <- df_eval_optim |>
  rename("waterlog.100" = "df_test.waterlog.100")
```

```{r}
conf_matrix_optim <- confusionMatrix(
  data = df_eval_optim$pred,
  reference = as.factor(df_eval_optim$waterlog.100),
  dnn = c("Predicted", "Observed")
)
conf_matrix_optim
```

# Probabilistic predictions

## Train probabilistic model

```{r}
rf_prob <- ranger( 
  formula = factor(df_train[, target]) ~ ., # target variable
  data = df_train[, predictors_selected], # Predictor variables
  mtry = 10, # Given from chapter 5.1
  min.node.size = 50, # Given from chapter 5.1
  seed = 42, # Specify the seed for randomization to reproduce the same model again
  probability = TRUE, # yields a probability to be true
  num.threads = parallel::detectCores() - 1)

# quick report and performance of trained model object
rf_prob
```

## ROC curve

```{r}
rf_eval_prob <- predict(
  rf_prob, # RF model
  data = df_test, # Predictor data
  num.threads = parallel::detectCores() - 1
)

# Save predictions to validation df
df_eval_prob <- data.frame(df_test$waterlog.100)
df_eval_prob$pred_0 <- rf_eval_prob$predictions[, "0"]
df_eval_prob$pred_1 <- rf_eval_prob$predictions[, "1"]

# Rename column
df_eval_prob <- df_eval_prob |>
  rename("waterlog.100" = "df_test.waterlog.100")
```

```{r}
ggplot(data = df_eval_prob, aes(d = waterlog.100, m = pred_1)) +
  geom_roc(n.cuts = 0, labels = FALSE) + # Add ROC curve & remove label and marker
  geom_abline( # Random guess line 
    intercept = 0,
    slope = 1,
    linetype = "dashed"
  ) +
  labs(
    x = "False positive fraction",
    y = "True positive fraction",
    title = "Reicever-operating-characteristic curve"
  ) +
  theme_bw()
```

## Additional questions
