---
title: "re_MWSM"
author: "Flueckiger_Rubens"
date: "2025-12-09"
output: 
  html_document:
    toc: TRUE
    toc_float:
      collapsed: FALSE
      smoth_scroll: FALSE
---

# Packages

```{r packages}
library(caret)
library(dplyr)
library(ggplot2)
library(RColorBrewer)
library(recipes)
library(rnaturalearth)
library(rnaturalearthdata)
library(sf)
library(themis)
```

# Datasets

```{r datasets}
df_test <- readr::read_csv("../data_raw/competition2025_testing_data.csv")
df_train <- readr::read_csv("../data_raw/competition2025_training_data.csv")
df_sites <- readr::read_csv("../data_raw/fdk_site_info.csv")
```

## Data location

```{r check missing sites}
# Select all unique sites from test and training dataset in site info data
idx_site_test <- which(df_sites$sitename %in% df_test$site)
idx_site_train <- which(df_sites$sitename %in% df_train$site)

# Combine all sites into one list and select only these sites
idx_sites <- unique(c(idx_site_test, idx_site_train))
relevant_sites <- df_sites[idx_sites, ]

# Select all unique sites in test and training dataset
sites_test <- unique(df_test$site)
sites_train <- unique(df_train$site)

# Combine into one list
sites_all <- c(sites_train, sites_test)

# Select all sites without information
sites_all[!(sites_all %in% relevant_sites$sitename)]
```

```{r additional sites}
# Load information about missing sites
add_sites <- readr::read_csv("../data_raw/fdk_additional_sites.csv")

# Combine additional sites and present sites into one dataset
relevant_sites <- rbind(relevant_sites, add_sites)
```

```{r site location}
# get coast outline
coast <- rnaturalearth::ne_coastline(scale = 110, returnclass = "sf")

ggplot() +
  
  #Plot coastline
  geom_sf(data = coast, colour = "black", size = 0.2) +

  # set extent in longitude and latitude
  # to draw map strictly bounded by the specified extent
  coord_sf(ylim = c(-60, 80), expand = FALSE) + 

  # plot points on map
  geom_point(
    data = relevant_sites,
    aes(x = lon, y = lat),
    color = "red",
    size = 1
  ) +
  
  # Label adjustments
  labs(
    x = "", y = "",
    title = "Spatial distribution of sites in the test and training set"
  ) +
  
  theme_bw()
```

Centered arround US, EU and AUS

# Impute data

```{r spacial classification}
# Create a five fold cluster
set.seed(109)
cluster <- kmeans(
  relevant_sites[, c("lon", "lat")],
  centers = 5
)

# Add cluster classes to dataset
relevant_sites$class <- as.factor(cluster$cluster)

ggplot() +
  
  #Plot coastline
  geom_sf(data = coast, colour = "black", size = 0.2) +

  # set extent in longitude and latitude
  # to draw map strictly bounded by the specified extent
  coord_sf(ylim = c(-60, 80), expand = FALSE) + 

  # plot points on map
  geom_point(
    data = relevant_sites,
    aes(x = lon, y = lat, color = class),
    size = 1
  ) +
  
  # Colour points according to their class
  scale_color_manual(
    values = brewer.pal(n = 5, "Set1"),
    name = "Class"
  ) +
  
  # Enlarge point size of legend
  guides(color = guide_legend(override.aes = list(size = 2))) +
  
  # Label adjustments
  labs(
    x = "", y = "",
    title = "Spatial distribution of sites in the test and training set"
  ) +
  
  theme_bw()
```

Not ideal for spatial imputation

```{r random classification}
# Create random sample of 10'000 sites
set.seed(155)
idx <- sample(1:length(df_train$site), 10000)

# Check if all sites are included in subset
subset_sites <- unique(df_train[idx, "vegtype"])$vegtype
vegtypes <- unique(df_train$vegtype)
vegtypes[!(vegtypes %in% subset_sites)]
```

```{r fill NA train}
if(FALSE){
  
  # Set recipe
  pp_train <- recipe( # Set function to fill NA values
    flue ~ NR_B1 + NR_B2 + NR_B3 + NR_B4 + NR_B5 + NR_B6 + NR_B7 + LST + t2m_era5 + ssrd_era5 + pcwd_era5 + vegtype, 
    data = df_train # df containing these columns
  ) |> 
    step_impute_knn(all_predictors(), neighbors = 5) |> # KNN impute
    step_center(all_numeric_predictors()) |> # Normalise data
    step_scale(all_numeric_predictors()) # Normalise data
  
  # 'Train' recipe
  trained <- prep(
    pp_train, # recipe
    training = df_train[idx, ], # 'Train' on reduced training set
    verbose = TRUE # Return processing status
  )
  
  # Apply 'trained' recipe on training data to impute NA values
  train_data <- bake(trained, new_data = df_train)
  
  # Add necessary columns back to df
  data_train <- train_data |> mutate(
    site = df_train$site, # Site
    date = df_train$date, # Date of sample
    is_flue_drought = df_train$is_flue_drought, # Logical flue status
    cluster = df_train$cluster # Clusters
  ) 
  
  # Save imputed training file
  readr::write_csv(data_train, file = "../data_raw/mswm_train_imputed")
}
```

```{r fill NA test}
if(FALSE){
  
  # Set recipe
  pp_test <- recipe( # Set function to fill NA values
    flue ~ NR_B1 + NR_B2 + NR_B3 + NR_B4 + NR_B5 + NR_B6 + NR_B7 + LST + t2m_era5 + ssrd_era5 + pcwd_era5 + vegtype, 
    data = df_train # df containing these columns
  ) |> 
    step_dummy(vegtype, keep_original_cols = TRUE) |> # test contains additional vegtypes
    step_impute_knn(all_predictors(), neighbors = 5) |> # KNN imputation
    step_center(all_numeric_predictors()) |> # Normalise data
    step_scale(all_numeric_predictors()) # Normalise data
  
  # 'Train' recipe
  trained_test <- prep(
    pp_test, # recipe
    training = df_train[idx, ], # Train on reduced training set
    verbose = TRUE # Return processing status
  )

  # Apply 'trained' recipe on test set to fill NA values
  test_data <- bake(trained_test, new_data = df_test)
  
  data_test <- test_data[, c(1:12)] |> mutate( # Select only necessary columns
    site = df_test$site, # Add site column
    date = df_test$date, # Add date column
    is_flue_drought = df_test$is_flue_drought, # Add drought status column
    cluster = df_test$cluster # Add cluster column
  )
  
  # Save imputed test file
  readr::write_csv(data_test, file = "../data_raw/mswm_test_imputed") 
}
```

<<<<<<< HEAD
# Modelling

```{r cv recipe}
set.seed(155) # Set seed
folds <- caret::groupKFold(df_train_upsamp$flue, k = 5) # prepare folds

traincntrlParams <- caret::trainControl( # Set fold settings
  index = folds,
  method = "cv"
)
```

```{r set predictors}
# Select predictors
predictors <- c(
  "NR_B1", "NR_B2", "NR_B3", "NR_B4", "NR_B5", "NR_B6", "NR_B7",
  "LST", "t2m_era5", "ssrd_era5", "pcwd_era5", "vegtype"
)

# Create string with all variables
fun_pred <- paste(
  c("flue ~", paste(predictors, collapse = " + ")),
  collapse = " "
)

# Convert into a caret-readable string
fun_pred <- formula(fun_pred)
```

```{r model}
mod_cv <- caret::train(
  fun_pred, # Model function
  data = df_train_upsamp, # training set
  method = "ranger", # Random Forest model
  trControl = traincntrlParams,
  tuneGrid = data.frame(
    .mtry = 3, 
    .min.node.size = 5,
    .splitrule = "variance"
  )
)
```

```{r predict}
# Predict values
pred <- predict(
  mod_cv,
  newdata = df_test_imp
)
```

```{r save result}
# Convert data into df format
predicted_flue <- data.frame(pred)

# Save df
# Note: to not overwrite LULC prediction I have added the name of the repo
# and renamed it after loading it into the folder
readr::write_csv(
  x = dplyr::rename(predicted_flue,
                    flue_predicted = pred),
  file = "~/Desktop/VanEend_results_mswm.csv")
```

# Upsample

```{r load imputed data}
# Load imputed files
df_test_imp <- readr::read_csv("../data_raw/mswm_test_imputed")
df_train_imp <- readr::read_csv("../data_raw/mswm_train_imputed")
```

```{r impute is_flue_drought}
# Check for NA values for drought status
flue_idx_na <- which(is.na(df_train_imp$is_flue_drought) == T)

# Impute drought status column
# Note: flue < 1 = TRUE (it is a drought)
for(i in 1:length(flue_idx_na)){
  ifelse(
    df_train_imp[flue_idx_na[i], "flue"] < 1,
    df_train_imp[flue_idx_na[i], "is_flue_drought"] <- TRUE,
    df_train_imp[flue_idx_na[i], "is_flue_drought"] <- FALSE
  )
}
```

```{r original ratio}
# Distribution of drought and moist before upsampling
orig <- count(df_train_imp, is_flue_drought, name = "orig")

# Create table
knitr::kable(
  orig, # df
  align = "lc", # Information position
  caption = "Table 1: Amount of fLUE moist (FALSE) and drought (TRUE) observation", # Table caption
  col.names = c("is fLUE drought", "Original dataset") # Column names
)
```

```{r upsampling}
# Change is_flue_drought values to factor format
df_train_imp_adj <- df_train_imp |> mutate(
  is_flue_drought = as.factor(is_flue_drought)
)

# upsampling recipe
pp_upsample <- recipe(
  is_flue_drought ~ ., # Set function 
  data = df_train_imp_adj # df
) |> themis::step_upsample(
    is_flue_drought, # Column to consider
    over_ratio = 0.5 # Final ratio between major and minor class
) |> prep() # 'Train' recipe

# Apply 'trained' recipe
df_train_upsamp <- bake(pp_upsample, new_data = NULL)
```

```{r upsampled ratio}
# Distribution of drought and not drought after upsampling
upsamp <- count(df_train_upsamp, is_flue_drought, name = "upsamp")

# Combine upsample and original ratio information
stat <- cbind(orig, upsamp)[, c(1, 2, 4)] # Only select relevant columns

# Create table
knitr::kable(
  stat, # df
  align = "lcc", # Information position
  caption = "Table 2: Comparing amount of fLUE moist (FALSE) and drought (TRUE) observation before and after upsampling", # Table caption
  col.names = c("is fLUE drought", "Original dataset", "Upsampled dataset") # Column names
)
```

# Modelling

```{r cv recipe}
set.seed(155) # Set seed
folds <- caret::groupKFold(df_train_upsamp$flue, k = 5) # prepare folds

traincntrlParams <- caret::trainControl( # Set fold settings
  index = folds,
  method = "cv"
)
```

```{r set predictors}
# Select predictors
predictors <- c(
  "NR_B1", "NR_B2", "NR_B3", "NR_B4", "NR_B5", "NR_B6", "NR_B7",
  "LST", "t2m_era5", "ssrd_era5", "pcwd_era5", "vegtype"
)

# Create string with all variables
fun_pred <- paste(
  c("flue ~", paste(predictors, collapse = " + ")),
  collapse = " "
)

# Convert into a caret-readable string
fun_pred <- formula(fun_pred)
```

```{r model}
mod_cv <- caret::train(
  fun_pred, # Model function
  data = df_train_upsamp, # training set
  method = "ranger", # Random Forest model
  trControl = traincntrlParams,
  tuneGrid = data.frame(
    .mtry = 3, 
    .min.node.size = 5,
    .splitrule = "variance"
  )
)
```

```{r predict, message=FALSE}
# Predict values
pred <- predict(
  mod_cv,
  newdata = df_test_imp
)
```

```{r save result}
# Convert data into df format
predicted_flue <- data.frame(pred)

# Save df
# Note: to not overwrite LULC prediction I have added the name of the repo
# and renamed it after loading it into the folder
readr::write_csv(
  x = dplyr::rename(predicted_flue,
                    flue_predicted = pred),
  file = "~/Desktop/VanEend_results_mswm.csv")
```
