---
title: "Spatial Upscalling"
author: "Flueckiger_Rubens"
date: "2025-11-24"
output: 
  html_document:
    toc: TRUE
    toc_float:
      collapsed: FALSE
      smooth_scroll: FALSE
---

# Packages and data

```{r packages, message=FALSE, warning=FALSE}
library(caret)
library(dplyr)
library(ggplot2)
library(ranger)
library(RColorBrewer)
library(rnaturalearth)
library(rnaturalearthdata)
library(sf)
library(skimr)
library(tidyverse)
```

```{r dataframe, message=FALSE}
if(FALSE){
  df <- readr::read_csv(
    "https://raw.githubusercontent.com/geco-bern/leafnp_data/main/data/leafnp_tian_et_al.csv")
  
  # Safe df for offline use
  write.csv(
    df,
    file = "../data_raw/leafnp_data", # Location
    row.names = FALSE # Don't save indices
  )
}

df <- readr::read_csv("../data_raw/leafnp_data")
```

## Data preprocessing

```{r df preprocessing}
common_species <- df |>
  group_by(Species) |>
  summarise(count = n()) |>
  arrange(desc(count)) |>
  slice(1:50) |>
  pull(Species)

dfs <- df |>
  dplyr::select(leafN, lon, lat, elv, mat, map, ndep, mai, Species) |>
  filter(Species %in% common_species)

# quick overview of data
skimr::skim(dfs)
```

# Random CV

```{r seed}
set.seed(102)
```

```{r model preprocessing}
# Select predictors
predictors <- names(dfs[4:ncol(dfs)])

# Create string with all variables
fun_pred <- paste(
  c("leafN ~", paste(predictors, collapse = " + ")),
  collapse = " "
)

# Convert into a caret-readable string
fun_pred <- formula(fun_pred)
```

```{r random cv}
mod_cv <- train(
  fun_pred, # Model function
  data = dfs, # training set
  method = "ranger", # Random Forest model
  trControl = trainControl(
    method = "cv", # Cross-Validation method
    number = 5 # 5-Fold CV
  ),
  tuneGrid = data.frame(
    .mtry = 3, # 
    .min.node.size = 12,
    .splitrule = "variance" # Default
  )
)

# Return metrics
stat <- mod_cv$resample[c("Rsquared", "RMSE")]
stat <- stat |> rename( # Rename row names
  "Rsq_ran" = "Rsquared",
  "RMSE_ran" = "RMSE"
) |> round(3) |> mutate( # Round observations
  "Fold" = mod_cv$resample["Resample"]# Fold number
) 

stat <- stat[c("Fold", "Rsq_ran", "RMSE_ran")] # Reorder columns

knitr::kable(
  stat, 
  align = "lcc",
  caption = "Table 2: R^2 and RMSE values from a random 5-fold CV"
)
```

# Spatial CV

## Observation distribution

```{r data distribution}
# get coast outline
coast <- rnaturalearth::ne_coastline(scale = 110, returnclass = "sf")

ggplot() +
  
  #Plot coastline
  geom_sf(data = coast, colour = "black", size = 0.2) +

  # set extent in longitude and latitude
  # to draw map strictly bounded by the specified extent
  coord_sf(ylim = c(-60, 80), expand = FALSE) + 

  # plot points on map
  geom_point(data = dfs, aes(x = lon, y = lat), color = "red", size = 0.2) +
  
  # Lable adjustments
  labs(
    x = "", y = "",
    title = "Spatial distribution of observations used in the dataset"
  ) +
  
  theme_bw() +
  theme(legend.position = "bottom")
```

## Spatial classification

```{r geo kmeans}
clusters <- kmeans(
  dfs[, c(2, 3)], # Lon and lat as clustering parameters
  centers = 5 # 5 clusters
)

# Include class to df. Note: convert into factor format
dfs$class_spat <- as.factor(clusters$cluster)
```

```{r plot geo clusters}
ggplot() +
  
  #Plot coastline
  geom_sf(data = coast, colour = "black", size = 0.2) +

  # set extent in longitude and latitude
  # to draw map strictly bounded by the specified extent
  coord_sf(ylim = c(-60, 80), expand = FALSE) + 

  # plot points on map
  geom_point(data = dfs, aes(
    x = lon, 
    y = lat,
    colour = class_spat 
  ), size = 0.2) +
  
  # Adjust point size of legend
  guides(color = guide_legend(override.aes = list(size = 2))) +
  
  # Set colour
  scale_color_manual(name = "Class", values = brewer.pal(n = 5, "Set1")) +

  # Lable adjustments
  labs(
    x = "", y = "",
    title = "Spatial distribution of observations used in the dataset",
    subtitle = "Classification according to geographical location"
  ) +
  
  theme_bw() + 
  theme(legend.position = "right")
```

```{r violin spat}
ggplot(data = dfs, aes(x = class_spat, y = leafN, fill = class_spat)) +
  geom_violin() + # Distribution using violin plot
  
  # Colour plot according to spatial distribution plot
  scale_fill_manual(values = brewer.pal(n = 5, "Set1")) +
  
  # Adding x & y axis label as well as title
  labs(
    x = "Class",
    y = "Leaf nitrogen",
    title = "Distribution of Leaf N over each class",
    subtitle = "Classification using geographical location"
  ) +
  
  theme_bw() +
  theme(legend.position = "") # Remove legend
```

## Function

```{r cv function}
# create a function that trains a random forest model on a given set of rows and
# predicts on a disjunct set of rows
train_test_by_fold <- function(df, idx_train, idx_val){
  
  # Split into training and testing set
  df_train <- df[idx_train, ] # training set
  df_test <- df[idx_val, ] # testing set
  
  mod <- ranger::ranger(
    formula = df_train[, 1] ~ ., # target
    data = df_train[, c(4:9)], # predictors
  )

  pred <- predict(
    mod, # model
    data = df_test[ , c(4:9)] # corresponding rows + predictors
  )
  
  # Combine obs and pred into 1 df
  df_test$pred <- pred$predictions
  
  # Calculate RMSE
  rmse <- Metrics::rmse(
    actual = df_test$leafN,
    predicted = df_test$pred
  ) |> round(3)

  # Calculate R2
  rsq <- cor(df_test$leafN, df_test$pred, method = "pearson")^2 |> round(3)

  return(tibble(rsq = rsq, rmse = rmse))
}
```

## Modelling

```{r split geo data}
# Return Indices of every class except searched one
group_folds_train <- purrr::map(
  seq(length(unique(dfs$class_spat))), # Amount of classes
  ~ {
    dfs |>
      select(class_spat) |> # Select one class
      mutate(idx = 1:n()) |> # Generate index column
      filter(class_spat != .) |> # Filter for classes which is not currently selected
      pull(idx) # store row index of these classes in idx column 
  }
)

# Return indices of searched class
group_folds_test <- purrr::map(
  seq(length(unique(dfs$class_spat))), # Amount of classes
  ~ {
    dfs |>
      select(class_spat) |> # Select one class
      mutate(idx = 1:n()) |> # Generate index column
      filter(class_spat == .) |> # Filter for index of currently selected class
      pull(idx) # Store row index of this class in idx column
  }
)
```

```{r geo cv}
out <- purrr::map2_dfr(
  group_folds_train,
  group_folds_test, 
  ~ train_test_by_fold(df = dfs, .x, .y) # Function
) |>
  mutate(test_fold = 1:5) # CV fold row
```

```{r table spat}
stat <- stat |> mutate( # Add spatial cv metrics
  "Rsq_spat" = out$rsq,
  "RMSE_spat" = out$rmse
)

stat <- stat[c( # Reorder columns
  "Fold",
  "Rsq_ran",
  "Rsq_spat",
  "RMSE_ran",
  "RMSE_spat"
)] 

knitr::kable(
  stat,
  align = "lcccc",
  caption = "Table 3: Compareing R^2 and RMSE value from random and spatial 5-fold CV"
)
```

# Environmental CV

## Environmental classification

```{r env kmeans}
clusters <- kmeans(
  dfs[, c(5, 6)], # Lon and lat as clustering parameters
  centers = 5 # 5 clusters
)

# Include class to df. Note: convert into factor format
dfs$class_env <- as.factor(clusters$cluster)
```

```{r plot env kmeans}
ggplot() +
  
  #Plot coastline
  geom_sf(data = coast, colour = "black", size = 0.2) +

  # set extent in longitude and latitude
  # to draw map strictly bounded by the specified extent
  coord_sf(ylim = c(-60, 80), expand = FALSE) + 

  # plot points on map
  geom_point(data = dfs, aes(
    x = lon, 
    y = lat,
    colour = class_env 
  ), size = 0.2) +
  
  # Adjust point size of legend
  guides(color = guide_legend(override.aes = list(size = 2))) +
  
  # Set colour
  scale_color_manual(name = "Class", values = brewer.pal(n = 5, "Set1")) +
  
  # Lable adjustments
  labs(
    x = "", y = "",
    title = "Spatial distribution of observations used in the dataset",
    subtitle = "Classification according to environmental conditions (T and Prec.)"
  ) +
  
  theme_bw() +
  theme(legend.position = "right")
```

```{r table, message=FALSE}
climate <- readr::read_csv("../data_raw/climate_table")

knitr::kable(
  climate,
  align = "lll",
  caption = "Table 4: Mean annual temperature and mean annual precipitation over all observations of a specific class",
  col.names = c("Class", "Average temperature [°C]", "Average precipitation [mm/yr]")
)
```

```{r violin env}
ggplot(data = dfs, aes(x = class_env, y = leafN, fill = class_env)) +
  geom_violin() + # Distribution using violin plot
  
  # Colour plot according to spatial distribution plot
  scale_fill_manual(values = brewer.pal(n = 5, "Set1")) +
  
  # Adding x & y axis label as well as title
  labs(
    x = "Class",
    y = "Leaf nitrogen",
    title = "Distribution of Leaf N over each class",
    subtitle = "Classification using environmental conditions (T and Prec.)"
  ) +
  
  theme_bw() +
  theme(legend.position = "") # Remove legend
```

## Modelling

```{r split env data}
# Return Index of every class except searched one
group_folds_train_2 <- purrr::map(
  seq(length(unique(dfs$class_env))),
  ~ {
    dfs |>
      select(class_env) |>
      mutate(idx = 1:n()) |>
      filter(class_env != .) |>
      pull(idx)
  }
)

# Return index of searched one
group_folds_test_2 <- purrr::map(
  seq(length(unique(dfs$class_env))),
  ~ {
    dfs |>
      select(class_env) |>
      mutate(idx = 1:n()) |>
      filter(class_env == .) |>
      pull(idx)
  }
)
```

```{r climate table, echo=FALSE}
if(FALSE){
  # Generate climatological table
  class <- seq(1:5) # Classes
  climate <- data.frame(class)
  
  for(i in 1:5){
    data <- dfs[group_folds_test_2[[i]], ] # Generate df for class
    
    climate[i, "Temperatue"] <- round(mean(data$mat), 3) # Mean temperature
    climate[i, "Precipitation"] <- round(mean(data$map), 3) # Mean precipitation
  }
  
  # Save file
  write.csv(
    climate,
    file = "../data_raw/climate_table",
    row.names = FALSE
  )
}
```

```{r env cv}
out_2 <- purrr::map2_dfr(
  group_folds_train_2,
  group_folds_test_2,
  ~ train_test_by_fold(df = dfs, .x, .y)
) |>
  mutate(test_fold = 1:5)
```

```{r table env}
stat <- stat |> mutate( # Add spatial cv metrics
  "Rsq_env" = out_2$rsq,
  "RMSE_env" = out_2$rmse
)

stat <- stat[c("Fold", # Reorder columns
  "Rsq_ran",
  "Rsq_spat",
  "Rsq_env",
  "RMSE_ran",
  "RMSE_spat",
  "RMSE_env"
)] 

knitr::kable(
  stat,
  align = "lcccccc",
  caption = "Figure 3: Compareing R^2 and RMSE value from random, spatial and environmental 5-fold CV"
)
```
